edition = "2021"
max_width = 80
indent_style = "Block"
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
binop_separator = "back"
tab_spaces = 2
use_small_heuristics = "Max"
use_field_init_shorthand = true
match_arm_leading_pipes = "Preserve"
merge_derives = true